### ISSUE TITLE
dim in ndfunc_arg_in_t

### ISSUE THREAD

**Issue by ohai** [ruby-numo/narray#17]
In my observation, "dim" field in ndfunc_arg_in_t is always 0.  What's this field?

**Comment by masa16** [comment]
It is the number of dimensions handled in a user iterator. If the argument is a matrix, dim=2. See Numo::Linalg https://github.com/ruby-numo/linalg/blob/master/ext/numo/linalg/gen/tmpl/matmul.c

**Comment by ohai** [comment]
Thank you for your reply. 
For example, when input array is ndim=3 and dim=2, the input array is considered to be a sequence of matrices. Is that correct?

**Comment by masa16** [comment]
Yes, right. It accepts array of matrix.

**Comment by ohai** [comment]
Thank you. 
I hope that tests for this functionality are added to the test suite of numo-narray.

Please close this issue.

**Comment by masa16** [comment]
Thank you for comments.
Testing and documentation are next issues.
