### ISSUE TITLE
Error SFloat is unknown for NMath

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/narray#24]
SFloat is unknown for NMath

```ruby
require 'numo/narray'
include Numo

x = SFloat[3.14]
p NMath.sin(x)
# "Numo::SFloat is unknown for Numo::NMath"

# Numo::SFloat#shape=[1]
# [0.00159255]
```

math.c
15+       EXTERN VALUE numo_mSFloatMath, numo_mDFloatMath, numo_mDComplexMath;
130+     rb_hash_aset(hCast, numo_cSFloat,   numo_mSFloatMath);

**Comment by masa16** [comment]
Thanks!
https://github.com/ruby-numo/narray/commit/e2092970defb6e028f7958aa414786ed2f93bbb5
