### ISSUE TITLE
Masking NArray using pre flattened one get the error. 

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/narray#28]
```ruby
require 'numo/narray'

a = Numo::UInt8.new(3,3).seq
b = a.flatten

b[b.eq 3] = 0
```
`inspect': invalid NA_TYPE of view: 2 (RuntimeError)

**Comment by kojix2** [comment]
flattened array is view...

**Comment by masa16** [comment]
This is a bug.
https://github.com/ruby-numo/narray/commit/0ddd65e377cdcf01159e2a990fb2b1bd3bf51f77
