### ISSUE TITLE
Some gem build warnings

### ISSUE THREAD

**Issue by DouglasAllen** [ruby-numo/narray#39]
$> gem build numo-narray.gemspec
WARNING:  open-ended dependency on rake-compiler (>= 1.0.1, development) is not recommended
  if rake-compiler is semantically versioned, use:
    add_development_dependency 'rake-compiler', '~> 1.0', '>= 1.0.1'
WARNING:  open-ended dependency on rake-compiler-dock (>= 0, development) is not recommended
  if rake-compiler-dock is semantically versioned, use:
    add_development_dependency 'rake-compiler-dock', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: numo-narray
  Version: 0.9.0.3
  File: numo-narray-0.9.0.3.gem

**Comment by masa16** [comment]
Fixed: https://github.com/ruby-numo/narray/commit/e8e9a2453fdd2aefe195305799df2fd4a0433b02
Thanks.
