### ISSUE TITLE
Does anyone need (more) precise sum ?

### ISSUE THREAD

**Issue by metanest** [ruby-numo/narray#40]
Does anyone need (more) precise sum ?

Ruby 2.4 has Enumerable#sum precise summing method, using Kahan summation algorithm ( https://en.wikipedia.org/wiki/Kahan_summation_algorithm , this is a lightweight and fast algorithm). Python 3's math.fsum is more precise. There are another proposals (ex. http://dx.doi.org/10.1137/030601818 ).

**Comment by metanest** [comment]
This is draft implementation, any comments are welcome.
https://github.com/ruby-numo/narray/compare/master...metanest:accurate_sum_draft_spike

**Comment by metanest** [comment]
final conversion of Bignum -> Float can simply done by bn.fdiv(1<<1074)

**Comment by masa16** [comment]
@metanest created kahan_sum method. Thanks.
