### ISSUE TITLE
How can I convert CvMat to Narray?

### ISSUE THREAD

**Issue by crcrpar** [ruby-numo/narray#41]
Hi, I want to convert CvMat to Narray like Numpy `np.asarray(image)`.
I checked TODO.md and I know there isn't `asarray` function.
Is there any alternative to convert CvMat to Narray object?

**Comment by masa16** [comment]
NArray has interface for conversion to/from Array and binary String object.
```ruby
require "numo/narray"

p Numo::UInt8.from_string("abcd",[2,2])
# => Numo::UInt8#shape=[2,2]
# [[97, 98], 
#  [99, 100]]

p Numo::DFloat.cast([[2,5],[7,8]])
# => Numo::DFloat#shape=[2,2]
# [[2, 5], 
#  [7, 8]]
```
So if it is possible to CvMat to Array or String object, you can convert CvMat to NArray.

**Comment by crcrpar** [comment]
Ok, I understood and I have another question. 
If I read image in binary data like `image = File.open("path/to/image", 'rb')`,
then can I convert `image` to `Numo::UInt8` variable?

Thank you.

**Comment by masa16** [comment]
For example,
```ruby
image = File.open("path/to/image", 'rb').read
narray = Numo::UInt8.from_string(image,shape)
```
Note that image shape should be given separately.

**Comment by crcrpar** [comment]
Thank you for your instruction.
I did read image to narray.
