### ISSUE TITLE
Undefined method `fill` when calling the NArray.zeros or NArray.ones method

### ISSUE THREAD

**Issue by toastystarfish** [ruby-numo/narray#43]
The documentation has a zeros and ones method on the NArray class, both have this error

**Comment by masa16** [comment]
Document says, "Returns a zero-filled narray with shape. This singleton method is valid not for NArray class itself but for typed NArray subclasses, e.g., DFloat, Int64."

**Comment by toastystarfish** [comment]
Ah, thank you using the subclasses works
