### ISSUE TITLE
weird result and segmentation fault when using Numo::Bit as an argument

### ISSUE THREAD

**Issue by lisleadam** [ruby-numo/narray#45]
weird result when giving as an argument Numo::Bit with all elments set to 0 to Numo::NArray.

example:
nar1=Numo::Int64[1,2,3,4,5]
nar2=Numo::Bit.zeros(5)
p nar1[nar2]
=> Numo::Int64(view)#shape=[0][]

besides, the following code causes segfault (or ruby stalls);
p nar1[nar2].min

confirmed in Ruby 2.4.0 & linux mint 18.1 64bit

**Comment by masa16** [comment]
As is shown in the following examples, this behavior is intended. 
```ruby
nar1 = Numo::Int64[1,2,3,4,5]

nar2 = Numo::Bit[1,1,1,1,1]
p nar1[nar2]
# => Numo::Int64(view)#shape=[5]
#    [1, 2, 3, 4, 5]

nar2 = Numo::Bit[1,1,1,0,0]
p nar1[nar2]
# => Numo::Int64(view)#shape=[3]
#    [1, 2, 3]

nar2 = Numo::Bit[1,0,0,0,0]
p nar1[nar2]
# => Numo::Int64(view)#shape=[1]
#    [1]

nar2 = Numo::Bit[0,0,0,0,0]
p nar1[nar2]
# => Numo::Int64(view)#shape=[0][]
```

Segfault problem is fixed in the latest commit. https://github.com/ruby-numo/narray/commit/f8c9958f1a676027b8a07b6ab8180c0c8f59340f
Thank you.
