### ISSUE TITLE
Possible inplace bug

### ISSUE THREAD

**Issue by lisleadam** [ruby-numo/narray#46]
I presume inplace dosen't set the inplace flag while inplace! does, but they seem to work just like the same;
```
na=Numo::DFloat.new(10).seq
na.inplace
na.inplace?
=> true
```

I'm not sure if this behaviour is intended, but if so the difference between inplace and inplace! is unclear.

**Comment by masa16** [comment]
Fixed: https://github.com/ruby-numo/narray/commit/852fa1dc513e951f77073e37d29ad08184328a7e
However, inplace is an experimental feature and its behaviour is not settled yet.
