### ISSUE TITLE
Project web contents which needs update

### ISSUE THREAD

**Issue by metanest** [ruby-numo/narray#49]
以下の場所にあるリンクが、古いリンクになっています。
- http://ruby-numo.github.io/narray/ の中にあるリンクのほとんどが、 https://github.com/masa16 以下にある、あるいは http://masa16.github.io/ 以下にある、URLへのリンクになっています
- https://github.com/ruby-numo/narray の最初の、プロジェクト紹介文「Ruby/Numo::NArray - New NArray class library http://masa16.github.io/narray/ 」のリンクが古いです

**Comment by masa16** [comment]
アップデートしました。
