### ISSUE TITLE
more RObject issues

### ISSUE THREAD

**Issue by lisleadam** [ruby-numo/narray#52]
thanks for your recent fixes to RObject issues.  unfortunately other issues arise (perhaps previous fixes were not enough?)

1) the following assignment raises exception
```
na=Numo::RObject.new(3).fill("a")
na[0..-1]="b"
=>Numo::NArray::CastError: unknown conversion from NilClass to Numo::RObject
```
this happens no matter what type of values you try to put, only exception being Numeric

2) Numo::RObject#eq (or ne) raises exception
```
na=Numo::RObject.new(3).fill("a")
na.eq "a"
=>NoMethodError: undefined method `cast' for nil:NilClass
na.eq :a
=>NoMethodError: undefined method `cast' for nil:NilClass

na2=Numo::RObject.new(3).fill(0)
na2.eq 0
=>NoMethodError: undefined method `eq' for 0:Integer

```

**Comment by masa16** [comment]
Recent commits will fix these problems. thx
