### ISSUE TITLE
`inplace` flag for Numo::GSL::Sf functions.

### ISSUE THREAD

**Issue by genya0407** [ruby-numo/narray#54]
`inplace` flag doesn't seem to work with functions defined in Numo::GSL::Sf.

```ruby
na = Numo::DFloat.new(3).fill 100
Numo::GSL::Sf.log_abs na.inplace
p na # => [100.0, 100.0, 100.0]
```

**Comment by masa16** [comment]
fixed: https://github.com/ruby-numo/gsl/commit/12d1d03a48e951c08445c301bd9c339688244b5c
