### ISSUE TITLE
random glitches in cast

### ISSUE THREAD

**Issue by lisleadam** [ruby-numo/narray#59]
since 0.9.5 (or possibly earlier?) NArray#cast sometimes causes segfault.  i tried to pinpoint the case but couldn't because the exact same ruby code in the exact same situation sometimes segfaults and other times not.  the glitch didn't happen when i ran the same code in march 2017 and in ruby 2.4.0.

this may not happen in 2.3.x or earlier (i use ruby 2.4.1 now and version 2.4.x doesn't seem to be officially supported yet) but i couldn't confirm that neither as my ruby application requires 2.4.x.  i'm still trying to find if this is actually an issue in numo/narray or it's just my ruby app that is the culprit.

**Comment by masa16** [comment]
This kind of symptom may be attributed to GC. The backtrace log on SEGV will be helpful for me to find a bug in NArray.

**Comment by masa16** [comment]
Latest commit will fix this problem.

**Comment by lisleadam** [comment]
it really did.  thanks a lot.  you made my day!
